-- ============================================================================
-- Sakan Alsayd Platform — combined migrations (regenerated)
-- ============================================================================
-- Generated by concatenating supabase/migrations/*.sql in numeric order.
-- This file is NOT the source of truth — the individual migration files in
-- supabase/migrations/ are. Re-run the regeneration command in CLAUDE.md if
-- you add a new migration. Use Supabase MCP apply_migration for actual applies.
-- ============================================================================


-- >>>>> migrations/001_schema.sql >>>>>
-- ============================================================================
-- Sakan Alsayd Platform - Database Schema Migration
-- ============================================================================
-- This migration creates the complete database schema including:
--   - 12 custom enum types
--   - 15 tables with full constraints and relationships
--   - updated_at trigger function applied to all mutable tables
--   - Indexes for common query patterns
-- ============================================================================

-- ============================================================================
-- ENUMS
-- ============================================================================

CREATE TYPE user_role AS ENUM (
  'super_admin',
  'branch_manager',
  'maintenance_staff',
  'transportation_staff',
  'supervision_staff',
  'finance_staff'
);

CREATE TYPE room_type AS ENUM (
  'single',
  'double',
  'triple',
  'suite'
);

CREATE TYPE bathroom_type AS ENUM (
  'shared',
  'shared-a',
  'shared-b',
  'shared-balcony',
  'private',
  'private-balcony',
  'private-two-rooms',
  'master',
  'master-a',
  'master-b',
  'master-balcony',
  'suite'
);

CREATE TYPE room_status AS ENUM (
  'available',
  'occupied',
  'maintenance',
  'reserved'
);

CREATE TYPE resident_status AS ENUM (
  'active',
  'checked_out',
  'suspended'
);

CREATE TYPE assignment_status AS ENUM (
  'active',
  'ended'
);

CREATE TYPE booking_status AS ENUM (
  'new',
  'contacted',
  'confirmed',
  'rejected'
);

CREATE TYPE maintenance_category AS ENUM (
  'plumbing',
  'electrical',
  'furniture',
  'cleaning',
  'hvac',
  'general'
);

CREATE TYPE maintenance_priority AS ENUM (
  'low',
  'medium',
  'high',
  'urgent'
);

CREATE TYPE maintenance_status AS ENUM (
  'submitted',
  'assigned',
  'in_progress',
  'completed',
  'cancelled'
);

CREATE TYPE testimonial_type AS ENUM (
  'quote',
  'screenshot',
  'video'
);

CREATE TYPE screenshot_source AS ENUM (
  'google_maps',
  'twitter',
  'instagram',
  'whatsapp',
  'other'
);

-- ============================================================================
-- TRIGGER FUNCTION: auto-update updated_at
-- ============================================================================

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================================================
-- TABLE 1: staff_profiles
-- ============================================================================

CREATE TABLE staff_profiles (
  id          UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name   TEXT NOT NULL,
  phone       TEXT,
  role        user_role NOT NULL DEFAULT 'supervision_staff',
  is_active   BOOLEAN NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_staff_profiles_updated_at
  BEFORE UPDATE ON staff_profiles
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- TABLE 2: buildings
-- ============================================================================

CREATE TABLE buildings (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  slug             TEXT UNIQUE NOT NULL,
  city_en          TEXT NOT NULL,
  city_ar          TEXT NOT NULL,
  neighborhood_en  TEXT NOT NULL,
  neighborhood_ar  TEXT NOT NULL,
  description_en   TEXT NOT NULL DEFAULT '',
  description_ar   TEXT NOT NULL DEFAULT '',
  cover_image      TEXT,
  images           TEXT[] DEFAULT '{}',
  map_url          TEXT,
  landmarks        JSONB NOT NULL DEFAULT '[]',
  is_active        BOOLEAN NOT NULL DEFAULT true,
  is_placeholder   BOOLEAN NOT NULL DEFAULT false,
  sort_order       INTEGER NOT NULL DEFAULT 0,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_buildings_updated_at
  BEFORE UPDATE ON buildings
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- TABLE 3: staff_building_assignments
-- ============================================================================

CREATE TABLE staff_building_assignments (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  staff_id     UUID NOT NULL REFERENCES staff_profiles(id) ON DELETE CASCADE,
  building_id  UUID NOT NULL REFERENCES buildings(id) ON DELETE CASCADE,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE(staff_id, building_id)
);

-- ============================================================================
-- TABLE 4: rooms
-- ============================================================================

CREATE TABLE rooms (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  building_id      UUID NOT NULL REFERENCES buildings(id) ON DELETE CASCADE,
  room_number      TEXT,
  floor            INTEGER,
  room_type        room_type NOT NULL,
  bathroom_type    bathroom_type NOT NULL,
  monthly_price    NUMERIC(10,2) NOT NULL,
  discounted_price NUMERIC(10,2),
  status           room_status NOT NULL DEFAULT 'available',
  images           TEXT[] DEFAULT '{}',
  notes            TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_rooms_updated_at
  BEFORE UPDATE ON rooms
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- TABLE 5: residents
-- ============================================================================

CREATE TABLE residents (
  id                       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  full_name                TEXT NOT NULL,
  phone                    TEXT NOT NULL,
  email                    TEXT,
  national_id_or_iqama     TEXT,
  nationality              TEXT,
  university_or_workplace  TEXT,
  emergency_contact_name   TEXT,
  emergency_contact_phone  TEXT,
  profile_image            TEXT,
  documents                TEXT[] DEFAULT '{}',
  status                   resident_status NOT NULL DEFAULT 'active',
  notes                    TEXT,
  created_at               TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at               TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_residents_updated_at
  BEFORE UPDATE ON residents
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- TABLE 6: room_assignments
-- ============================================================================

CREATE TABLE room_assignments (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  resident_id     UUID NOT NULL REFERENCES residents(id) ON DELETE RESTRICT,
  room_id         UUID NOT NULL REFERENCES rooms(id) ON DELETE RESTRICT,
  building_id     UUID NOT NULL REFERENCES buildings(id) ON DELETE RESTRICT,
  check_in_date   DATE NOT NULL,
  check_out_date  DATE,
  status          assignment_status NOT NULL DEFAULT 'active',
  created_by      UUID REFERENCES staff_profiles(id) ON DELETE SET NULL,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_room_assignments_updated_at
  BEFORE UPDATE ON room_assignments
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- TABLE 7: booking_requests
-- ============================================================================

CREATE TABLE booking_requests (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name             TEXT NOT NULL,
  email            TEXT NOT NULL,
  phone            TEXT NOT NULL,
  city_interested  TEXT NOT NULL,
  message          TEXT,
  status           booking_status NOT NULL DEFAULT 'new',
  assigned_to      UUID REFERENCES staff_profiles(id) ON DELETE SET NULL,
  notes            TEXT,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_booking_requests_updated_at
  BEFORE UPDATE ON booking_requests
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- TABLE 8: booking_request_notes
-- ============================================================================

CREATE TABLE booking_request_notes (
  id                  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_request_id  UUID NOT NULL REFERENCES booking_requests(id) ON DELETE CASCADE,
  author_id           UUID NOT NULL REFERENCES staff_profiles(id) ON DELETE SET NULL,
  note                TEXT NOT NULL,
  created_at          TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- TABLE 9: maintenance_requests
-- ============================================================================

CREATE TABLE maintenance_requests (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  building_id       UUID NOT NULL REFERENCES buildings(id) ON DELETE RESTRICT,
  room_id           UUID REFERENCES rooms(id) ON DELETE SET NULL,
  resident_id       UUID REFERENCES residents(id) ON DELETE SET NULL,
  title             TEXT NOT NULL,
  description       TEXT,
  category          maintenance_category NOT NULL DEFAULT 'general',
  priority          maintenance_priority NOT NULL DEFAULT 'medium',
  status            maintenance_status NOT NULL DEFAULT 'submitted',
  assigned_to       UUID REFERENCES staff_profiles(id) ON DELETE SET NULL,
  photos            TEXT[] DEFAULT '{}',
  resolution_notes  TEXT,
  created_by        UUID REFERENCES staff_profiles(id) ON DELETE SET NULL,
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at        TIMESTAMPTZ NOT NULL DEFAULT now(),
  completed_at      TIMESTAMPTZ
);

CREATE TRIGGER trg_maintenance_requests_updated_at
  BEFORE UPDATE ON maintenance_requests
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- TABLE 10: cms_services
-- ============================================================================

CREATE TABLE cms_services (
  id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  icon_name       TEXT NOT NULL,
  title_ar        TEXT NOT NULL,
  title_en        TEXT NOT NULL,
  description_ar  TEXT NOT NULL,
  description_en  TEXT NOT NULL,
  sort_order      INTEGER NOT NULL DEFAULT 0,
  is_active       BOOLEAN NOT NULL DEFAULT true,
  created_at      TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at      TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_cms_services_updated_at
  BEFORE UPDATE ON cms_services
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- TABLE 11: cms_testimonials
-- ============================================================================

CREATE TABLE cms_testimonials (
  id               UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type             testimonial_type NOT NULL,
  name             TEXT,
  name_ar          TEXT,
  building         TEXT,
  building_ar      TEXT,
  city             TEXT,
  city_ar          TEXT,
  quote_en         TEXT,
  quote_ar         TEXT,
  rating           INTEGER CHECK (rating >= 1 AND rating <= 5),
  avatar_url       TEXT,
  source           screenshot_source,
  source_label     TEXT,
  source_label_ar  TEXT,
  screenshot_url   TEXT,
  alt_text         TEXT,
  alt_text_ar      TEXT,
  video_title      TEXT,
  video_title_ar   TEXT,
  thumbnail_url    TEXT,
  youtube_id       TEXT,
  duration         TEXT,
  is_featured      BOOLEAN NOT NULL DEFAULT false,
  sort_order       INTEGER NOT NULL DEFAULT 0,
  is_active        BOOLEAN NOT NULL DEFAULT true,
  created_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_cms_testimonials_updated_at
  BEFORE UPDATE ON cms_testimonials
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- TABLE 12: cms_faq
-- ============================================================================

CREATE TABLE cms_faq (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  question_ar  TEXT NOT NULL,
  question_en  TEXT NOT NULL,
  answer_ar    TEXT NOT NULL,
  answer_en    TEXT NOT NULL,
  sort_order   INTEGER NOT NULL DEFAULT 0,
  is_active    BOOLEAN NOT NULL DEFAULT true,
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_cms_faq_updated_at
  BEFORE UPDATE ON cms_faq
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- TABLE 13: cms_contacts
-- ============================================================================

CREATE TABLE cms_contacts (
  id          UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  type_en     TEXT NOT NULL,
  type_ar     TEXT NOT NULL,
  phone       TEXT NOT NULL,
  whatsapp    TEXT,
  sort_order  INTEGER NOT NULL DEFAULT 0,
  is_active   BOOLEAN NOT NULL DEFAULT true,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_cms_contacts_updated_at
  BEFORE UPDATE ON cms_contacts
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- TABLE 14: site_config
-- ============================================================================

CREATE TABLE site_config (
  key         TEXT PRIMARY KEY,
  value       JSONB NOT NULL,
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TRIGGER trg_site_config_updated_at
  BEFORE UPDATE ON site_config
  FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- ============================================================================
-- TABLE 15: activity_log
-- ============================================================================

CREATE TABLE activity_log (
  id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      UUID REFERENCES staff_profiles(id) ON DELETE SET NULL,
  action       TEXT NOT NULL,
  entity_type  TEXT NOT NULL,
  entity_id    UUID,
  details      JSONB DEFAULT '{}',
  created_at   TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- ============================================================================
-- INDEXES
-- ============================================================================

-- staff_profiles
CREATE INDEX idx_staff_profiles_role      ON staff_profiles (role);
CREATE INDEX idx_staff_profiles_is_active ON staff_profiles (is_active);

-- buildings
CREATE INDEX idx_buildings_slug       ON buildings (slug);
CREATE INDEX idx_buildings_city_en    ON buildings (city_en);
CREATE INDEX idx_buildings_is_active  ON buildings (is_active);
CREATE INDEX idx_buildings_sort_order ON buildings (sort_order);

-- rooms
CREATE INDEX idx_rooms_building_id            ON rooms (building_id);
CREATE INDEX idx_rooms_status                 ON rooms (status);
CREATE INDEX idx_rooms_room_type              ON rooms (room_type);
CREATE INDEX idx_rooms_building_id_status     ON rooms (building_id, status);
CREATE INDEX idx_rooms_building_id_room_type  ON rooms (building_id, room_type);

-- residents
CREATE INDEX idx_residents_status               ON residents (status);
CREATE INDEX idx_residents_phone                ON residents (phone);
CREATE INDEX idx_residents_national_id_or_iqama ON residents (national_id_or_iqama);
CREATE INDEX idx_residents_full_name            ON residents (full_name);

-- room_assignments
CREATE INDEX idx_room_assignments_resident_id    ON room_assignments (resident_id);
CREATE INDEX idx_room_assignments_room_id        ON room_assignments (room_id);
CREATE INDEX idx_room_assignments_building_id    ON room_assignments (building_id);
CREATE INDEX idx_room_assignments_status         ON room_assignments (status);
CREATE INDEX idx_room_assignments_bldg_active    ON room_assignments (building_id, status) WHERE status = 'active';
CREATE INDEX idx_room_assignments_dates          ON room_assignments (check_in_date, check_out_date);

-- booking_requests
CREATE INDEX idx_booking_requests_status          ON booking_requests (status);
CREATE INDEX idx_booking_requests_assigned_to     ON booking_requests (assigned_to);
CREATE INDEX idx_booking_requests_created_at      ON booking_requests (created_at DESC);
CREATE INDEX idx_booking_requests_city_interested ON booking_requests (city_interested);

-- booking_request_notes
CREATE INDEX idx_booking_request_notes_request_id  ON booking_request_notes (booking_request_id);
CREATE INDEX idx_booking_request_notes_created_at  ON booking_request_notes (created_at DESC);

-- maintenance_requests
CREATE INDEX idx_maintenance_requests_building_id       ON maintenance_requests (building_id);
CREATE INDEX idx_maintenance_requests_room_id           ON maintenance_requests (room_id);
CREATE INDEX idx_maintenance_requests_resident_id       ON maintenance_requests (resident_id);
CREATE INDEX idx_maintenance_requests_status            ON maintenance_requests (status);
CREATE INDEX idx_maintenance_requests_priority          ON maintenance_requests (priority);
CREATE INDEX idx_maintenance_requests_assigned_to       ON maintenance_requests (assigned_to);
CREATE INDEX idx_maintenance_requests_category          ON maintenance_requests (category);
CREATE INDEX idx_maintenance_requests_bldg_status       ON maintenance_requests (building_id, status);
CREATE INDEX idx_maintenance_requests_created_at        ON maintenance_requests (created_at DESC);

-- cms_services
CREATE INDEX idx_cms_services_sort_active ON cms_services (sort_order) WHERE is_active = true;

-- cms_testimonials
CREATE INDEX idx_cms_testimonials_sort_active  ON cms_testimonials (sort_order) WHERE is_active = true;
CREATE INDEX idx_cms_testimonials_type         ON cms_testimonials (type);
CREATE INDEX idx_cms_testimonials_featured     ON cms_testimonials (is_featured) WHERE is_featured = true;

-- cms_faq
CREATE INDEX idx_cms_faq_sort_active ON cms_faq (sort_order) WHERE is_active = true;

-- cms_contacts
CREATE INDEX idx_cms_contacts_sort_active ON cms_contacts (sort_order) WHERE is_active = true;

-- activity_log
CREATE INDEX idx_activity_log_user_id     ON activity_log (user_id);
CREATE INDEX idx_activity_log_entity      ON activity_log (entity_type, entity_id);
CREATE INDEX idx_activity_log_created_at  ON activity_log (created_at DESC);
CREATE INDEX idx_activity_log_action      ON activity_log (action);

-- staff_building_assignments
CREATE INDEX idx_staff_building_assignments_staff_id    ON staff_building_assignments (staff_id);
CREATE INDEX idx_staff_building_assignments_building_id ON staff_building_assignments (building_id);


-- >>>>> migrations/002_rls.sql >>>>>
-- ============================================================================
-- Sakan Alsayd Platform - Row Level Security Policies
-- ============================================================================

-- ============================================================================
-- HELPER FUNCTIONS
-- ============================================================================

CREATE OR REPLACE FUNCTION public.get_user_role()
RETURNS user_role AS $$
  SELECT role FROM public.staff_profiles WHERE id = auth.uid();
$$ LANGUAGE sql SECURITY DEFINER STABLE;

CREATE OR REPLACE FUNCTION public.is_super_admin()
RETURNS BOOLEAN AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.staff_profiles
    WHERE id = auth.uid() AND role = 'super_admin' AND is_active = true
  );
$$ LANGUAGE sql SECURITY DEFINER STABLE;

CREATE OR REPLACE FUNCTION public.is_assigned_to_building(p_building_id UUID)
RETURNS BOOLEAN AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.staff_building_assignments
    WHERE staff_id = auth.uid() AND building_id = p_building_id
  );
$$ LANGUAGE sql SECURITY DEFINER STABLE;

-- ============================================================================
-- ENABLE RLS ON ALL TABLES
-- ============================================================================

ALTER TABLE public.staff_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.staff_building_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.buildings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.residents ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.room_assignments ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.booking_request_notes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.maintenance_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cms_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cms_testimonials ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cms_faq ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.cms_contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.site_config ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.activity_log ENABLE ROW LEVEL SECURITY;

-- ============================================================================
-- STAFF_PROFILES
-- ============================================================================

CREATE POLICY "staff_select_all" ON public.staff_profiles
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "staff_update_own" ON public.staff_profiles
  FOR UPDATE TO authenticated
  USING (id = auth.uid())
  WITH CHECK (id = auth.uid());

CREATE POLICY "staff_admin_insert" ON public.staff_profiles
  FOR INSERT TO authenticated
  WITH CHECK (public.is_super_admin());

CREATE POLICY "staff_admin_update" ON public.staff_profiles
  FOR UPDATE TO authenticated
  USING (public.is_super_admin());

CREATE POLICY "staff_admin_delete" ON public.staff_profiles
  FOR DELETE TO authenticated
  USING (public.is_super_admin());

-- ============================================================================
-- STAFF_BUILDING_ASSIGNMENTS
-- ============================================================================

CREATE POLICY "sba_select_all" ON public.staff_building_assignments
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "sba_admin_all" ON public.staff_building_assignments
  FOR ALL TO authenticated
  USING (public.is_super_admin())
  WITH CHECK (public.is_super_admin());

-- ============================================================================
-- BUILDINGS
-- ============================================================================

CREATE POLICY "buildings_auth_select" ON public.buildings
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "buildings_anon_select" ON public.buildings
  FOR SELECT TO anon USING (is_active = true);

CREATE POLICY "buildings_admin_all" ON public.buildings
  FOR ALL TO authenticated
  USING (public.is_super_admin())
  WITH CHECK (public.is_super_admin());

CREATE POLICY "buildings_manager_update" ON public.buildings
  FOR UPDATE TO authenticated
  USING (public.is_assigned_to_building(id))
  WITH CHECK (public.is_assigned_to_building(id));

-- ============================================================================
-- ROOMS
-- ============================================================================

CREATE POLICY "rooms_auth_select" ON public.rooms
  FOR SELECT TO authenticated USING (true);

CREATE POLICY "rooms_anon_select" ON public.rooms
  FOR SELECT TO anon
  USING (EXISTS (SELECT 1 FROM public.buildings b WHERE b.id = building_id AND b.is_active = true));

CREATE POLICY "rooms_admin_all" ON public.rooms
  FOR ALL TO authenticated
  USING (public.is_super_admin())
  WITH CHECK (public.is_super_admin());

CREATE POLICY "rooms_manager_insert" ON public.rooms
  FOR INSERT TO authenticated
  WITH CHECK (public.is_assigned_to_building(building_id));

CREATE POLICY "rooms_manager_update" ON public.rooms
  FOR UPDATE TO authenticated
  USING (public.is_assigned_to_building(building_id))
  WITH CHECK (public.is_assigned_to_building(building_id));

CREATE POLICY "rooms_manager_delete" ON public.rooms
  FOR DELETE TO authenticated
  USING (public.is_assigned_to_building(building_id));

-- ============================================================================
-- RESIDENTS
-- ============================================================================

CREATE POLICY "residents_admin_all" ON public.residents
  FOR ALL TO authenticated
  USING (public.is_super_admin())
  WITH CHECK (public.is_super_admin());

CREATE POLICY "residents_manager_select" ON public.residents
  FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.room_assignments ra
      JOIN public.staff_building_assignments sba ON sba.building_id = ra.building_id
      WHERE ra.resident_id = residents.id AND sba.staff_id = auth.uid()
    )
  );

CREATE POLICY "residents_manager_insert" ON public.residents
  FOR INSERT TO authenticated
  WITH CHECK (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) IN ('branch_manager', 'supervision_staff')
  );

CREATE POLICY "residents_manager_update" ON public.residents
  FOR UPDATE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.room_assignments ra
      JOIN public.staff_building_assignments sba ON sba.building_id = ra.building_id
      WHERE ra.resident_id = residents.id AND sba.staff_id = auth.uid()
    )
  );

-- ============================================================================
-- ROOM_ASSIGNMENTS
-- ============================================================================

CREATE POLICY "assignments_admin_all" ON public.room_assignments
  FOR ALL TO authenticated
  USING (public.is_super_admin())
  WITH CHECK (public.is_super_admin());

CREATE POLICY "assignments_manager_select" ON public.room_assignments
  FOR SELECT TO authenticated
  USING (public.is_assigned_to_building(building_id));

CREATE POLICY "assignments_manager_insert" ON public.room_assignments
  FOR INSERT TO authenticated
  WITH CHECK (public.is_assigned_to_building(building_id));

CREATE POLICY "assignments_manager_update" ON public.room_assignments
  FOR UPDATE TO authenticated
  USING (public.is_assigned_to_building(building_id))
  WITH CHECK (public.is_assigned_to_building(building_id));

-- ============================================================================
-- BOOKING_REQUESTS
-- ============================================================================

-- Anonymous can insert (website contact form)
CREATE POLICY "bookings_anon_insert" ON public.booking_requests
  FOR INSERT TO anon WITH CHECK (true);

CREATE POLICY "bookings_auth_insert" ON public.booking_requests
  FOR INSERT TO authenticated WITH CHECK (true);

CREATE POLICY "bookings_admin_all" ON public.booking_requests
  FOR ALL TO authenticated
  USING (public.is_super_admin())
  WITH CHECK (public.is_super_admin());

CREATE POLICY "bookings_staff_select" ON public.booking_requests
  FOR SELECT TO authenticated
  USING (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) IN
      ('branch_manager', 'supervision_staff', 'finance_staff')
  );

CREATE POLICY "bookings_staff_update" ON public.booking_requests
  FOR UPDATE TO authenticated
  USING (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) IN
      ('branch_manager', 'supervision_staff')
  );

-- ============================================================================
-- BOOKING_REQUEST_NOTES
-- ============================================================================

CREATE POLICY "booking_notes_admin_all" ON public.booking_request_notes
  FOR ALL TO authenticated
  USING (public.is_super_admin())
  WITH CHECK (public.is_super_admin());

CREATE POLICY "booking_notes_staff_select" ON public.booking_request_notes
  FOR SELECT TO authenticated
  USING (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) IN
      ('branch_manager', 'supervision_staff', 'finance_staff')
  );

CREATE POLICY "booking_notes_staff_insert" ON public.booking_request_notes
  FOR INSERT TO authenticated
  WITH CHECK (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) IN
      ('branch_manager', 'supervision_staff', 'finance_staff')
  );

-- ============================================================================
-- MAINTENANCE_REQUESTS
-- ============================================================================

CREATE POLICY "maintenance_admin_all" ON public.maintenance_requests
  FOR ALL TO authenticated
  USING (public.is_super_admin())
  WITH CHECK (public.is_super_admin());

CREATE POLICY "maintenance_manager_select" ON public.maintenance_requests
  FOR SELECT TO authenticated
  USING (public.is_assigned_to_building(building_id));

CREATE POLICY "maintenance_manager_insert" ON public.maintenance_requests
  FOR INSERT TO authenticated
  WITH CHECK (public.is_assigned_to_building(building_id));

CREATE POLICY "maintenance_manager_update" ON public.maintenance_requests
  FOR UPDATE TO authenticated
  USING (public.is_assigned_to_building(building_id));

CREATE POLICY "maintenance_manager_delete" ON public.maintenance_requests
  FOR DELETE TO authenticated
  USING (public.is_assigned_to_building(building_id));

CREATE POLICY "maintenance_staff_select" ON public.maintenance_requests
  FOR SELECT TO authenticated
  USING (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) = 'maintenance_staff'
    AND public.is_assigned_to_building(building_id)
  );

CREATE POLICY "maintenance_staff_update" ON public.maintenance_requests
  FOR UPDATE TO authenticated
  USING (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) = 'maintenance_staff'
    AND assigned_to = auth.uid()
  );

CREATE POLICY "maintenance_supervision_select" ON public.maintenance_requests
  FOR SELECT TO authenticated
  USING (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) = 'supervision_staff'
    AND public.is_assigned_to_building(building_id)
  );

CREATE POLICY "maintenance_supervision_insert" ON public.maintenance_requests
  FOR INSERT TO authenticated
  WITH CHECK (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) = 'supervision_staff'
    AND public.is_assigned_to_building(building_id)
  );

-- ============================================================================
-- CMS TABLES (public read for website, admin write)
-- ============================================================================

-- cms_services
CREATE POLICY "cms_services_anon_select" ON public.cms_services
  FOR SELECT TO anon USING (is_active = true);
CREATE POLICY "cms_services_auth_select" ON public.cms_services
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "cms_services_admin_all" ON public.cms_services
  FOR ALL TO authenticated
  USING (public.is_super_admin()) WITH CHECK (public.is_super_admin());

-- cms_testimonials
CREATE POLICY "cms_testimonials_anon_select" ON public.cms_testimonials
  FOR SELECT TO anon USING (is_active = true);
CREATE POLICY "cms_testimonials_auth_select" ON public.cms_testimonials
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "cms_testimonials_admin_all" ON public.cms_testimonials
  FOR ALL TO authenticated
  USING (public.is_super_admin()) WITH CHECK (public.is_super_admin());

-- cms_faq
CREATE POLICY "cms_faq_anon_select" ON public.cms_faq
  FOR SELECT TO anon USING (is_active = true);
CREATE POLICY "cms_faq_auth_select" ON public.cms_faq
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "cms_faq_admin_all" ON public.cms_faq
  FOR ALL TO authenticated
  USING (public.is_super_admin()) WITH CHECK (public.is_super_admin());

-- cms_contacts
CREATE POLICY "cms_contacts_anon_select" ON public.cms_contacts
  FOR SELECT TO anon USING (is_active = true);
CREATE POLICY "cms_contacts_auth_select" ON public.cms_contacts
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "cms_contacts_admin_all" ON public.cms_contacts
  FOR ALL TO authenticated
  USING (public.is_super_admin()) WITH CHECK (public.is_super_admin());

-- site_config
CREATE POLICY "site_config_anon_select" ON public.site_config
  FOR SELECT TO anon USING (true);
CREATE POLICY "site_config_auth_select" ON public.site_config
  FOR SELECT TO authenticated USING (true);
CREATE POLICY "site_config_admin_all" ON public.site_config
  FOR ALL TO authenticated
  USING (public.is_super_admin()) WITH CHECK (public.is_super_admin());

-- ============================================================================
-- ACTIVITY_LOG (append-only)
-- ============================================================================

CREATE POLICY "activity_log_admin_select" ON public.activity_log
  FOR SELECT TO authenticated
  USING (public.is_super_admin());

CREATE POLICY "activity_log_insert" ON public.activity_log
  FOR INSERT TO authenticated
  WITH CHECK (user_id = auth.uid());


-- >>>>> migrations/003_maintenance_updates.sql >>>>>
-- ============================================================================
-- Migration 003: Maintenance Updates
-- ============================================================================
-- Adds requester contact columns to maintenance_requests (for public submissions)
-- Creates maintenance_request_notes table (for internal staff notes)
-- ============================================================================

-- ============================================================================
-- 1. ADD REQUESTER COLUMNS TO maintenance_requests
-- ============================================================================

ALTER TABLE maintenance_requests
  ADD COLUMN requester_name  TEXT,
  ADD COLUMN requester_phone TEXT,
  ADD COLUMN room_number     TEXT;

-- ============================================================================
-- 2. CREATE maintenance_request_notes TABLE
-- ============================================================================

CREATE TABLE maintenance_request_notes (
  id                      UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  maintenance_request_id  UUID NOT NULL REFERENCES maintenance_requests(id) ON DELETE CASCADE,
  author_id               UUID NOT NULL REFERENCES staff_profiles(id) ON DELETE SET NULL,
  note                    TEXT NOT NULL,
  created_at              TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Indexes
CREATE INDEX idx_maintenance_request_notes_request_id ON maintenance_request_notes (maintenance_request_id);
CREATE INDEX idx_maintenance_request_notes_created_at ON maintenance_request_notes (created_at DESC);

-- ============================================================================
-- 3. RLS FOR maintenance_request_notes
-- ============================================================================

ALTER TABLE public.maintenance_request_notes ENABLE ROW LEVEL SECURITY;

-- Super admin: full access
CREATE POLICY "maintenance_notes_admin_all" ON public.maintenance_request_notes
  FOR ALL TO authenticated
  USING (public.is_super_admin())
  WITH CHECK (public.is_super_admin());

-- Staff: select (branch_manager, supervision_staff, maintenance_staff)
CREATE POLICY "maintenance_notes_staff_select" ON public.maintenance_request_notes
  FOR SELECT TO authenticated
  USING (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) IN
      ('branch_manager', 'supervision_staff', 'maintenance_staff')
  );

-- Staff: insert (branch_manager, supervision_staff, maintenance_staff)
CREATE POLICY "maintenance_notes_staff_insert" ON public.maintenance_request_notes
  FOR INSERT TO authenticated
  WITH CHECK (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) IN
      ('branch_manager', 'supervision_staff', 'maintenance_staff')
  );


-- >>>>> migrations/004_booking_pipeline.sql >>>>>
-- Migration 004: Booking Pipeline Upgrade
-- Adds new status values to support 3-department handoff workflow:
-- Customer Service → Finance → Supervision

-- Add new status values to existing enum
ALTER TYPE booking_status ADD VALUE IF NOT EXISTS 'in_review';
ALTER TYPE booking_status ADD VALUE IF NOT EXISTS 'pending_payment';
ALTER TYPE booking_status ADD VALUE IF NOT EXISTS 'pending_onboarding';
ALTER TYPE booking_status ADD VALUE IF NOT EXISTS 'completed';
ALTER TYPE booking_status ADD VALUE IF NOT EXISTS 'cancelled';

-- Migrate existing data from old statuses to new ones
UPDATE booking_requests SET status = 'in_review' WHERE status = 'contacted';
UPDATE booking_requests SET status = 'completed' WHERE status = 'confirmed';


-- >>>>> migrations/005_add_rejected_maintenance_status.sql >>>>>
-- Add 'rejected' status to maintenance_status enum
-- Allows staff to formally reject a maintenance request (reviewed and denied)
-- as distinct from 'cancelled' (withdrawn or voided)
ALTER TYPE maintenance_status ADD VALUE IF NOT EXISTS 'rejected' AFTER 'completed';


-- >>>>> migrations/006_booking_extended_fields.sql >>>>>
-- Add new columns to booking_requests for extended booking form
ALTER TABLE booking_requests ADD COLUMN IF NOT EXISTS date_of_birth DATE;
ALTER TABLE booking_requests ADD COLUMN IF NOT EXISTS occupation TEXT;
ALTER TABLE booking_requests ADD COLUMN IF NOT EXISTS emergency_contact_name TEXT;
ALTER TABLE booking_requests ADD COLUMN IF NOT EXISTS emergency_contact_phone TEXT;
ALTER TABLE booking_requests ADD COLUMN IF NOT EXISTS contract_start_date DATE;
ALTER TABLE booking_requests ADD COLUMN IF NOT EXISTS with_transportation BOOLEAN DEFAULT false;
ALTER TABLE booking_requests ADD COLUMN IF NOT EXISTS metadata JSONB DEFAULT '{}';


-- >>>>> migrations/007_maintenance_photos_bucket.sql >>>>>
-- ============================================================================
-- Migration 007: Create maintenance-photos storage bucket
-- ============================================================================
-- Creates a private storage bucket for maintenance request photo uploads.
-- Bucket config: 5MB limit, JPEG/PNG/WebP only, private (signed URLs).
-- ============================================================================

-- 1. Create the bucket
INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES (
  'maintenance-photos',
  'maintenance-photos',
  false,
  5242880,
  ARRAY['image/jpeg', 'image/png', 'image/webp']
)
ON CONFLICT (id) DO NOTHING;

-- 2. Allow authenticated users to read objects (needed for signed URL generation)
CREATE POLICY "Authenticated users can read maintenance photos"
ON storage.objects FOR SELECT TO authenticated
USING (bucket_id = 'maintenance-photos');

-- 3. Allow authenticated staff to upload photos to existing requests
CREATE POLICY "Staff can upload maintenance photos"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (bucket_id = 'maintenance-photos');


-- >>>>> migrations/008_maintenance_photos_rls.sql >>>>>
-- ============================================================================
-- Migration 008: Tighten RLS for maintenance-photos storage bucket
-- ============================================================================
-- Replaces the permissive INSERT policy from migration 007 (which allowed any
-- authenticated user to upload to any path in the bucket) with a policy that
-- binds uploads to either the 'temp/' staging folder or an existing maintenance
-- request UUID. Also adds UPDATE/DELETE policies for privileged roles so
-- orphan photos can actually be cleaned up.
-- ============================================================================

-- 1. Drop the permissive INSERT policy from 007
DROP POLICY IF EXISTS "Staff can upload maintenance photos" ON storage.objects;

-- 2. Allow INSERT only when the path prefix is either 'temp' or an existing request UUID
CREATE POLICY "Staff can upload maintenance photos (bound to request)"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (
  bucket_id = 'maintenance-photos'
  AND (
    split_part(name, '/', 1) = 'temp'
    OR EXISTS (
      SELECT 1 FROM public.maintenance_requests
      WHERE id::text = split_part(name, '/', 1)
    )
  )
);

-- 3. Allow DELETE only to privileged roles (cleanup, reorganisation)
CREATE POLICY "Privileged staff can delete maintenance photos"
ON storage.objects FOR DELETE TO authenticated
USING (
  bucket_id = 'maintenance-photos'
  AND EXISTS (
    SELECT 1 FROM public.staff_profiles
    WHERE id = auth.uid()
      AND is_active
      AND role IN ('super_admin', 'branch_manager', 'maintenance_staff')
  )
);

-- 4. Allow UPDATE only to privileged roles (rename/move)
CREATE POLICY "Privileged staff can update maintenance photos"
ON storage.objects FOR UPDATE TO authenticated
USING (
  bucket_id = 'maintenance-photos'
  AND EXISTS (
    SELECT 1 FROM public.staff_profiles
    WHERE id = auth.uid()
      AND is_active
      AND role IN ('super_admin', 'branch_manager', 'maintenance_staff')
  )
);


-- >>>>> migrations/009_maintenance_summary_refactor.sql >>>>>
-- ============================================================================
-- Migration 009: Maintenance Summary Refactor
-- ============================================================================
-- Retires `title` as a required field on maintenance_requests. The short
-- description becomes the primary summary (≤150 chars, enforced at the
-- application layer), and a new `extra_details` column captures long-form
-- text when the summary isn't enough.
--
-- The `title` column is kept (made nullable) to preserve historical data and
-- allow easy rollback. A one-time backfill copies title into description for
-- any legacy row whose description is empty, so the admin Summary column
-- isn't blank for existing records.
-- ============================================================================

ALTER TABLE maintenance_requests
  ALTER COLUMN title DROP NOT NULL;

ALTER TABLE maintenance_requests
  ADD COLUMN IF NOT EXISTS extra_details TEXT;

UPDATE maintenance_requests
SET description = LEFT(title, 150)
WHERE (description IS NULL OR description = '')
  AND title IS NOT NULL
  AND title <> '';


-- >>>>> migrations/010_protect_last_super_admin.sql >>>>>
-- ============================================================================
-- Protect against losing the last active super_admin under concurrent writes.
--
-- The user-management API previously enforced this with an application-level
-- count + update, which is racy: two concurrent demotions of two different
-- active super_admins both pass the count check and both succeed, leaving
-- zero active super_admins. We move the guard into the database:
--
--   1. A trigger BEFORE UPDATE on staff_profiles aborts any update that
--      would leave the count of (role='super_admin' AND is_active=true)
--      at zero. The trigger uses an advisory lock to serialize concurrent
--      updates that touch the super_admin pool, eliminating the TOCTOU race.
--   2. An SECURITY DEFINER RPC `update_staff_profile_safely` that the API
--      can call to perform updates atomically and surface a friendly error
--      code (`last_super_admin`) instead of a raw SQL exception string.
-- ============================================================================

-- Stable lock id derived from a salted hash of "staff_profiles:super_admin_pool".
-- pg_advisory_xact_lock takes a bigint; any deterministic id works.
CREATE OR REPLACE FUNCTION public._super_admin_lock()
RETURNS void AS $$
  SELECT pg_advisory_xact_lock(8675309001::bigint);
$$ LANGUAGE sql;

CREATE OR REPLACE FUNCTION public.protect_last_super_admin()
RETURNS trigger AS $$
DECLARE
  remaining_count integer;
BEGIN
  -- Only relevant if this update could remove an active super_admin.
  IF OLD.role = 'super_admin' AND OLD.is_active = true
     AND (NEW.role <> 'super_admin' OR NEW.is_active = false) THEN

    -- Serialize all updates that affect the super_admin pool inside the
    -- transaction. Concurrent updates wait here.
    PERFORM public._super_admin_lock();

    SELECT count(*) INTO remaining_count
    FROM public.staff_profiles
    WHERE role = 'super_admin'
      AND is_active = true
      AND id <> OLD.id;

    IF remaining_count = 0 THEN
      RAISE EXCEPTION 'last_super_admin'
        USING ERRCODE = 'check_violation';
    END IF;
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_protect_last_super_admin ON public.staff_profiles;
CREATE TRIGGER trg_protect_last_super_admin
  BEFORE UPDATE OF role, is_active ON public.staff_profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.protect_last_super_admin();

-- Same protection for hard deletes (in case anyone bypasses the API and
-- runs a raw DELETE — the API itself returns 405, but defense in depth).
CREATE OR REPLACE FUNCTION public.protect_last_super_admin_on_delete()
RETURNS trigger AS $$
DECLARE
  remaining_count integer;
BEGIN
  IF OLD.role = 'super_admin' AND OLD.is_active = true THEN
    PERFORM public._super_admin_lock();

    SELECT count(*) INTO remaining_count
    FROM public.staff_profiles
    WHERE role = 'super_admin'
      AND is_active = true
      AND id <> OLD.id;

    IF remaining_count = 0 THEN
      RAISE EXCEPTION 'last_super_admin'
        USING ERRCODE = 'check_violation';
    END IF;
  END IF;

  RETURN OLD;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_protect_last_super_admin_delete ON public.staff_profiles;
CREATE TRIGGER trg_protect_last_super_admin_delete
  BEFORE DELETE ON public.staff_profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.protect_last_super_admin_on_delete();


-- >>>>> migrations/011_role_expansion_enum.sql >>>>>
-- ============================================================================
-- Migration 011: Role expansion — add 4 new values to user_role enum
-- ============================================================================
-- Adds department-manager tier and a deputy-GM role above branch_manager.
--   - maintenance_manager       (peer of maintenance_staff, manager tier)
--   - transportation_manager    (peer of transportation_staff, manager tier)
--   - finance_manager           (peer of finance_staff, manager tier)
--   - deputy_general_manager    (super_admin-equivalent, except user mgmt)
--
-- Postgres allows ADD VALUE inside a transaction, but the new values cannot
-- be referenced in the SAME transaction. RLS policy updates that reference
-- these values therefore live in migration 012.
-- ============================================================================

ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'maintenance_manager';
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'transportation_manager';
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'finance_manager';
ALTER TYPE user_role ADD VALUE IF NOT EXISTS 'deputy_general_manager';


-- >>>>> migrations/012_role_expansion_rls.sql >>>>>
-- ============================================================================
-- Migration 012: Role expansion — RLS updates for new roles
-- ============================================================================
-- Mirrors the access of department-manager roles to their staff counterpart,
-- and grants deputy_general_manager super_admin-equivalent access to every
-- table EXCEPT staff_profiles (user management remains super_admin only).
--
-- Strategy:
--   1. New helper has_admin_access() = role IN ('super_admin','deputy_general_manager')
--   2. Replace each existing `*_admin_all` policy that was using is_super_admin()
--      with one that uses has_admin_access(), EXCEPT for staff_profiles policies.
--   3. Extend role-list policies (e.g. bookings_staff_select) to include the
--      manager peer of each staff role they reference.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1. Helper: has_admin_access() — super_admin OR deputy_general_manager
-- ----------------------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.has_admin_access()
RETURNS BOOLEAN AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.staff_profiles
    WHERE id = auth.uid()
      AND role IN ('super_admin', 'deputy_general_manager')
      AND is_active = true
  );
$$ LANGUAGE sql SECURITY DEFINER STABLE;

-- ----------------------------------------------------------------------------
-- 2. Replace `*_admin_all` policies on non-staff-profile tables
--    (staff_profiles user-management policies stay restricted to super_admin)
-- ----------------------------------------------------------------------------

-- staff_building_assignments
DROP POLICY IF EXISTS "sba_admin_all" ON public.staff_building_assignments;
CREATE POLICY "sba_admin_all" ON public.staff_building_assignments
  FOR ALL TO authenticated
  USING (public.has_admin_access())
  WITH CHECK (public.has_admin_access());

-- buildings
DROP POLICY IF EXISTS "buildings_admin_all" ON public.buildings;
CREATE POLICY "buildings_admin_all" ON public.buildings
  FOR ALL TO authenticated
  USING (public.has_admin_access())
  WITH CHECK (public.has_admin_access());

-- rooms
DROP POLICY IF EXISTS "rooms_admin_all" ON public.rooms;
CREATE POLICY "rooms_admin_all" ON public.rooms
  FOR ALL TO authenticated
  USING (public.has_admin_access())
  WITH CHECK (public.has_admin_access());

-- residents
DROP POLICY IF EXISTS "residents_admin_all" ON public.residents;
CREATE POLICY "residents_admin_all" ON public.residents
  FOR ALL TO authenticated
  USING (public.has_admin_access())
  WITH CHECK (public.has_admin_access());

-- room_assignments
DROP POLICY IF EXISTS "assignments_admin_all" ON public.room_assignments;
CREATE POLICY "assignments_admin_all" ON public.room_assignments
  FOR ALL TO authenticated
  USING (public.has_admin_access())
  WITH CHECK (public.has_admin_access());

-- booking_requests
DROP POLICY IF EXISTS "bookings_admin_all" ON public.booking_requests;
CREATE POLICY "bookings_admin_all" ON public.booking_requests
  FOR ALL TO authenticated
  USING (public.has_admin_access())
  WITH CHECK (public.has_admin_access());

-- booking_request_notes
DROP POLICY IF EXISTS "booking_notes_admin_all" ON public.booking_request_notes;
CREATE POLICY "booking_notes_admin_all" ON public.booking_request_notes
  FOR ALL TO authenticated
  USING (public.has_admin_access())
  WITH CHECK (public.has_admin_access());

-- maintenance_requests
DROP POLICY IF EXISTS "maintenance_admin_all" ON public.maintenance_requests;
CREATE POLICY "maintenance_admin_all" ON public.maintenance_requests
  FOR ALL TO authenticated
  USING (public.has_admin_access())
  WITH CHECK (public.has_admin_access());

-- maintenance_request_notes
DROP POLICY IF EXISTS "maintenance_notes_admin_all" ON public.maintenance_request_notes;
CREATE POLICY "maintenance_notes_admin_all" ON public.maintenance_request_notes
  FOR ALL TO authenticated
  USING (public.has_admin_access())
  WITH CHECK (public.has_admin_access());

-- cms_services
DROP POLICY IF EXISTS "cms_services_admin_all" ON public.cms_services;
CREATE POLICY "cms_services_admin_all" ON public.cms_services
  FOR ALL TO authenticated
  USING (public.has_admin_access())
  WITH CHECK (public.has_admin_access());

-- cms_testimonials
DROP POLICY IF EXISTS "cms_testimonials_admin_all" ON public.cms_testimonials;
CREATE POLICY "cms_testimonials_admin_all" ON public.cms_testimonials
  FOR ALL TO authenticated
  USING (public.has_admin_access())
  WITH CHECK (public.has_admin_access());

-- cms_faq
DROP POLICY IF EXISTS "cms_faq_admin_all" ON public.cms_faq;
CREATE POLICY "cms_faq_admin_all" ON public.cms_faq
  FOR ALL TO authenticated
  USING (public.has_admin_access())
  WITH CHECK (public.has_admin_access());

-- cms_contacts
DROP POLICY IF EXISTS "cms_contacts_admin_all" ON public.cms_contacts;
CREATE POLICY "cms_contacts_admin_all" ON public.cms_contacts
  FOR ALL TO authenticated
  USING (public.has_admin_access())
  WITH CHECK (public.has_admin_access());

-- site_config
DROP POLICY IF EXISTS "site_config_admin_all" ON public.site_config;
CREATE POLICY "site_config_admin_all" ON public.site_config
  FOR ALL TO authenticated
  USING (public.has_admin_access())
  WITH CHECK (public.has_admin_access());

-- activity_log
DROP POLICY IF EXISTS "activity_log_admin_select" ON public.activity_log;
CREATE POLICY "activity_log_admin_select" ON public.activity_log
  FOR SELECT TO authenticated
  USING (public.has_admin_access());

-- ----------------------------------------------------------------------------
-- 3. Extend role-list policies to include manager peers of staff roles
-- ----------------------------------------------------------------------------

-- booking_requests: finance_staff + finance_manager peer access
DROP POLICY IF EXISTS "bookings_staff_select" ON public.booking_requests;
CREATE POLICY "bookings_staff_select" ON public.booking_requests
  FOR SELECT TO authenticated
  USING (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) IN
      ('branch_manager', 'supervision_staff', 'finance_staff', 'finance_manager')
  );

-- (bookings_staff_update keeps the same role list — finance_staff was not in it)

-- booking_request_notes: add finance_manager
DROP POLICY IF EXISTS "booking_notes_staff_select" ON public.booking_request_notes;
CREATE POLICY "booking_notes_staff_select" ON public.booking_request_notes
  FOR SELECT TO authenticated
  USING (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) IN
      ('branch_manager', 'supervision_staff', 'finance_staff', 'finance_manager')
  );

DROP POLICY IF EXISTS "booking_notes_staff_insert" ON public.booking_request_notes;
CREATE POLICY "booking_notes_staff_insert" ON public.booking_request_notes
  FOR INSERT TO authenticated
  WITH CHECK (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) IN
      ('branch_manager', 'supervision_staff', 'finance_staff', 'finance_manager')
  );

-- maintenance_requests: add maintenance_manager peer
DROP POLICY IF EXISTS "maintenance_staff_select" ON public.maintenance_requests;
CREATE POLICY "maintenance_staff_select" ON public.maintenance_requests
  FOR SELECT TO authenticated
  USING (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) IN
      ('maintenance_staff', 'maintenance_manager')
    AND public.is_assigned_to_building(building_id)
  );

DROP POLICY IF EXISTS "maintenance_staff_update" ON public.maintenance_requests;
CREATE POLICY "maintenance_staff_update" ON public.maintenance_requests
  FOR UPDATE TO authenticated
  USING (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) IN
      ('maintenance_staff', 'maintenance_manager')
    AND assigned_to = auth.uid()
  );

-- maintenance_request_notes: add maintenance_manager
DROP POLICY IF EXISTS "maintenance_notes_staff_select" ON public.maintenance_request_notes;
CREATE POLICY "maintenance_notes_staff_select" ON public.maintenance_request_notes
  FOR SELECT TO authenticated
  USING (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) IN
      ('branch_manager', 'supervision_staff', 'maintenance_staff', 'maintenance_manager')
  );

DROP POLICY IF EXISTS "maintenance_notes_staff_insert" ON public.maintenance_request_notes;
CREATE POLICY "maintenance_notes_staff_insert" ON public.maintenance_request_notes
  FOR INSERT TO authenticated
  WITH CHECK (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) IN
      ('branch_manager', 'supervision_staff', 'maintenance_staff', 'maintenance_manager')
  );

-- ----------------------------------------------------------------------------
-- 4. maintenance-photos storage bucket: include maintenance_manager + deputy
-- ----------------------------------------------------------------------------

DROP POLICY IF EXISTS "Privileged staff can delete maintenance photos" ON storage.objects;
CREATE POLICY "Privileged staff can delete maintenance photos"
ON storage.objects FOR DELETE TO authenticated
USING (
  bucket_id = 'maintenance-photos'
  AND EXISTS (
    SELECT 1 FROM public.staff_profiles
    WHERE id = auth.uid()
      AND is_active
      AND role IN (
        'super_admin', 'deputy_general_manager',
        'branch_manager', 'maintenance_staff', 'maintenance_manager'
      )
  )
);

DROP POLICY IF EXISTS "Privileged staff can update maintenance photos" ON storage.objects;
CREATE POLICY "Privileged staff can update maintenance photos"
ON storage.objects FOR UPDATE TO authenticated
USING (
  bucket_id = 'maintenance-photos'
  AND EXISTS (
    SELECT 1 FROM public.staff_profiles
    WHERE id = auth.uid()
      AND is_active
      AND role IN (
        'super_admin', 'deputy_general_manager',
        'branch_manager', 'maintenance_staff', 'maintenance_manager'
      )
  )
);


-- >>>>> migrations/013_role_expansion_followup.sql >>>>>
-- ============================================================================
-- Migration 013: Role expansion follow-up — close gaps surfaced by review
-- ============================================================================
-- Three classes of fixes:
--
--   1. CRITICAL — block self-promotion via the staff_update_own RLS policy.
--      The existing policy lets users UPDATE any column on their own row.
--      With deputy_general_manager added in 011/012 (a near-super_admin tier),
--      a non-admin user could self-promote via the cookie-bound supabase
--      client and instantly gain has_admin_access() across the data plane.
--      We add a BEFORE UPDATE trigger that aborts when auth.uid() = OLD.id
--      AND role/is_active changes. The admin API uses createAdminClient
--      (service role; auth.uid() = NULL), so legitimate admin updates pass.
--
--   2. CRITICAL/HIGH — tighten the legacy `*_manager_*` RLS policies that
--      were named after `branch_manager` but never role-checked. Any building-
--      assigned user (now including the new manager-tier roles) inherited
--      cross-domain CRUD on buildings/rooms/residents/room_assignments and
--      maintenance_requests. We add an explicit `branch_manager` role guard
--      to each so the design intent ("manager peer == staff peer access")
--      holds and the new role-restricted policies in 012 stop being shadowed.
--
--   3. HIGH — finance must be able to advance bookings from pending_payment
--      to pending_onboarding. bookings_staff_update was kept at
--      branch_manager + supervision_staff in 012, but the API + UI both
--      surface the transition for finance roles. Add finance_staff and
--      finance_manager.
--
--   4. MEDIUM — the storage bucket INSERT policy in 008 had no role gate;
--      any authenticated user could upload to maintenance-photos via a
--      direct supabase client call. Add a maintenance-tier role guard.
--
-- Production note: this migration depends on 011/012 having been applied
-- (it references the new enum values). Apply 010→013 together if shipping
-- to a project that's still on the pre-expansion baseline.
-- ============================================================================


-- ----------------------------------------------------------------------------
-- 1. Trigger: block self-modification of role / is_active
-- ----------------------------------------------------------------------------
-- The admin API at /api/admin/users/[id] already returns `selfModify` 400
-- when the caller targets their own row. This trigger is the database-level
-- backstop against direct-RLS self-promotion.

CREATE OR REPLACE FUNCTION public.prevent_self_role_or_active_change()
RETURNS trigger AS $$
BEGIN
  IF auth.uid() IS NOT NULL
     AND auth.uid() = OLD.id
     AND (NEW.role IS DISTINCT FROM OLD.role
          OR NEW.is_active IS DISTINCT FROM OLD.is_active) THEN
    RAISE EXCEPTION 'cannot_self_modify_role_or_active'
      USING ERRCODE = 'check_violation';
  END IF;
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_prevent_self_role_or_active ON public.staff_profiles;
CREATE TRIGGER trg_prevent_self_role_or_active
  BEFORE UPDATE OF role, is_active ON public.staff_profiles
  FOR EACH ROW
  EXECUTE FUNCTION public.prevent_self_role_or_active_change();


-- ----------------------------------------------------------------------------
-- 2. Tighten legacy `*_manager_*` policies to require role = 'branch_manager'
-- ----------------------------------------------------------------------------
-- Before this migration, these policies checked only is_assigned_to_building().
-- After: the building-assignment check stands AND the caller must actually be
-- a branch_manager. has_admin_access() (via the *_admin_all policies on these
-- tables) continues to grant super_admin / deputy_general_manager unrestricted
-- access. The new manager-tier roles (maintenance_manager, transportation_
-- manager, finance_manager) drop back to their staff-peer access surface.

-- buildings
DROP POLICY IF EXISTS "buildings_manager_update" ON public.buildings;
CREATE POLICY "buildings_manager_update" ON public.buildings
  FOR UPDATE TO authenticated
  USING (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) = 'branch_manager'
    AND public.is_assigned_to_building(id)
  )
  WITH CHECK (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) = 'branch_manager'
    AND public.is_assigned_to_building(id)
  );

-- rooms
DROP POLICY IF EXISTS "rooms_manager_insert" ON public.rooms;
CREATE POLICY "rooms_manager_insert" ON public.rooms
  FOR INSERT TO authenticated
  WITH CHECK (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) = 'branch_manager'
    AND public.is_assigned_to_building(building_id)
  );

DROP POLICY IF EXISTS "rooms_manager_update" ON public.rooms;
CREATE POLICY "rooms_manager_update" ON public.rooms
  FOR UPDATE TO authenticated
  USING (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) = 'branch_manager'
    AND public.is_assigned_to_building(building_id)
  )
  WITH CHECK (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) = 'branch_manager'
    AND public.is_assigned_to_building(building_id)
  );

DROP POLICY IF EXISTS "rooms_manager_delete" ON public.rooms;
CREATE POLICY "rooms_manager_delete" ON public.rooms
  FOR DELETE TO authenticated
  USING (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) = 'branch_manager'
    AND public.is_assigned_to_building(building_id)
  );

-- residents
DROP POLICY IF EXISTS "residents_manager_select" ON public.residents;
CREATE POLICY "residents_manager_select" ON public.residents
  FOR SELECT TO authenticated
  USING (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) = 'branch_manager'
    AND EXISTS (
      SELECT 1 FROM public.room_assignments ra
      JOIN public.staff_building_assignments sba ON sba.building_id = ra.building_id
      WHERE ra.resident_id = residents.id AND sba.staff_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "residents_manager_update" ON public.residents;
CREATE POLICY "residents_manager_update" ON public.residents
  FOR UPDATE TO authenticated
  USING (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) = 'branch_manager'
    AND EXISTS (
      SELECT 1 FROM public.room_assignments ra
      JOIN public.staff_building_assignments sba ON sba.building_id = ra.building_id
      WHERE ra.resident_id = residents.id AND sba.staff_id = auth.uid()
    )
  );
-- residents_manager_insert is already role-gated (branch_manager + supervision_staff)
-- and stays as-is.

-- room_assignments
DROP POLICY IF EXISTS "assignments_manager_select" ON public.room_assignments;
CREATE POLICY "assignments_manager_select" ON public.room_assignments
  FOR SELECT TO authenticated
  USING (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) = 'branch_manager'
    AND public.is_assigned_to_building(building_id)
  );

DROP POLICY IF EXISTS "assignments_manager_insert" ON public.room_assignments;
CREATE POLICY "assignments_manager_insert" ON public.room_assignments
  FOR INSERT TO authenticated
  WITH CHECK (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) = 'branch_manager'
    AND public.is_assigned_to_building(building_id)
  );

DROP POLICY IF EXISTS "assignments_manager_update" ON public.room_assignments;
CREATE POLICY "assignments_manager_update" ON public.room_assignments
  FOR UPDATE TO authenticated
  USING (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) = 'branch_manager'
    AND public.is_assigned_to_building(building_id)
  )
  WITH CHECK (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) = 'branch_manager'
    AND public.is_assigned_to_building(building_id)
  );

-- maintenance_requests — branch_manager keeps building-wide CRUD here.
-- maintenance_staff / maintenance_manager retain their narrower policies
-- from 002 / 012 (staff_select with building, staff_update with assigned_to).
-- supervision_staff retains maintenance_supervision_select / _insert from 002.
DROP POLICY IF EXISTS "maintenance_manager_select" ON public.maintenance_requests;
CREATE POLICY "maintenance_manager_select" ON public.maintenance_requests
  FOR SELECT TO authenticated
  USING (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) = 'branch_manager'
    AND public.is_assigned_to_building(building_id)
  );

DROP POLICY IF EXISTS "maintenance_manager_insert" ON public.maintenance_requests;
CREATE POLICY "maintenance_manager_insert" ON public.maintenance_requests
  FOR INSERT TO authenticated
  WITH CHECK (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) = 'branch_manager'
    AND public.is_assigned_to_building(building_id)
  );

DROP POLICY IF EXISTS "maintenance_manager_update" ON public.maintenance_requests;
CREATE POLICY "maintenance_manager_update" ON public.maintenance_requests
  FOR UPDATE TO authenticated
  USING (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) = 'branch_manager'
    AND public.is_assigned_to_building(building_id)
  );

DROP POLICY IF EXISTS "maintenance_manager_delete" ON public.maintenance_requests;
CREATE POLICY "maintenance_manager_delete" ON public.maintenance_requests
  FOR DELETE TO authenticated
  USING (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) = 'branch_manager'
    AND public.is_assigned_to_building(building_id)
  );


-- ----------------------------------------------------------------------------
-- 3. bookings_staff_update: add finance_staff + finance_manager
-- ----------------------------------------------------------------------------
-- Finance receives bookings at status='pending_payment' and advances them
-- to 'pending_onboarding' once payment lands. They need UPDATE access.

DROP POLICY IF EXISTS "bookings_staff_update" ON public.booking_requests;
CREATE POLICY "bookings_staff_update" ON public.booking_requests
  FOR UPDATE TO authenticated
  USING (
    (SELECT role FROM public.staff_profiles WHERE id = auth.uid()) IN
      ('branch_manager', 'supervision_staff', 'finance_staff', 'finance_manager')
  );


-- ----------------------------------------------------------------------------
-- 4. maintenance-photos storage INSERT: require maintenance-tier role
-- ----------------------------------------------------------------------------
-- The path-prefix check from 008 stays. We add a role guard so a non-
-- maintenance authenticated user can't bypass the API and upload directly.
-- Public maintenance form uploads continue to work — they go through the
-- API's createAdminClient path (service role bypasses RLS).

DROP POLICY IF EXISTS "Staff can upload maintenance photos (bound to request)" ON storage.objects;
CREATE POLICY "Staff can upload maintenance photos (bound to request)"
ON storage.objects FOR INSERT TO authenticated
WITH CHECK (
  bucket_id = 'maintenance-photos'
  AND (
    split_part(name, '/', 1) = 'temp'
    OR EXISTS (
      SELECT 1 FROM public.maintenance_requests
      WHERE id::text = split_part(name, '/', 1)
    )
  )
  AND EXISTS (
    SELECT 1 FROM public.staff_profiles
    WHERE id = auth.uid()
      AND is_active
      AND role IN (
        'super_admin', 'deputy_general_manager',
        'branch_manager', 'maintenance_staff', 'maintenance_manager'
      )
  )
);

